export const metadata = {
  title: 'My Blogger Next.js',
  description: 'Generated by Gemini',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="el">
      <body>{children}</body>
    </html>
  )
}
