export const metadata = {
  title: 'My Blogger Next.js',
  description: 'Generated by Gemini',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="el">
    <body className="antialiased">
  <style>{`
    img { max-width: 100%; height: auto; border-radius: 8px; }
    iframe { max-width: 100%; }
    .prose { overflow-wrap: break-word; }
  `}</style>
  {children}
</body>
    </html>
  )
}
